### ISSUE TITLE
Proposal to rename this referrer-spam-list

### ISSUE THREAD

**Issue by kylerchin** [matomo-org/referrer-spam-list#1224]
There is a huge problem in tech where Black/White is used to mean allowing or denying. There is also a movement within tech to change this. That's why I'm asking you to change this repo's name as well as instances within composer.json and markdown files. Together, we can make Tech more inclusive.

Thanks,
Kyler

**Comment by tsteur** [comment]
👍 +1 

I'd even suggest simply `referrer-spam-list` as `blocklist` is not 100% inclusive either from what I've seen.

**Comment by kylerchin** [comment]
Got it, issue name changed, thanks! @tsteur

**Comment by tsteur** [comment]
Started the work in https://github.com/matomo-org/referrer-spam-list/pull/1225 and repo is renamed.

**Comment by aschrijver** [comment]
Thanks! On [awesome-humane-tech](https://github.com/humanetech-community/awesome-humane-tech) we used 'blocklists' for a while, except for those cases where 'blacklist' was part of the project name. I'll update our list.

Note that per [IETF Recommendation](https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.1.1) it is also advised to use `main` branch instead of `master`. I don't know about Github yet but for instance Gitea made this the default for new repositories.

**Comment by skylarmt** [comment]
People just make up racism where there isn't any. This is why we can't have nice things.
